### ISSUE TITLE
app install error

### ISSUE THREAD

**Issue by gprime31** [kiranreddyrebel/PostMessage_Fuzz_Tool#3]
![2021-12-07_08-52](https://user-images.githubusercontent.com/44535257/145041452-f9bc10ac-037b-4371-9723-bed3223197ac.png)

**Comment by gprime31** [comment]
![2021-12-07_08-53](https://user-images.githubusercontent.com/44535257/145041552-1cdfeb2f-1397-45e1-9cfc-71d747f86c5e.png)

**Comment by gprime31** [comment]
![2021-12-07_08-58](https://user-images.githubusercontent.com/44535257/145042515-ee75b1fc-4e37-42a2-827f-0934fac335c7.png)

**Comment by gprime31** [comment]
any ideas?

**Comment by gprime31** [comment]
also

**Comment by gprime31** [comment]
![2021-12-07_09-07](https://user-images.githubusercontent.com/44535257/145044023-ad9f2b3b-b8f2-4030-a5fc-99c7b49ef13c.png)

**Comment by gprime31** [comment]
![2021-12-07_09-08](https://user-images.githubusercontent.com/44535257/145044045-0905bb7d-a89b-4fef-969f-a4dbfd155155.png)

**Comment by gprime31** [comment]
![2021-12-07_09-09](https://user-images.githubusercontent.com/44535257/145044310-62458ad6-47ad-4ceb-bcfd-a2599b99f603.png)

**Comment by kiranreddyrebel** [comment]
Hi,
Click on Developer mode to ON

Then unzip the zip file you got inside repo and load it by clicking on
"load unpacked" button in chrome's extension page.

No need to worry about the errors. It will work fine. Now on right side
upper click on extension icon and pin the extension you want to be shown on
top.

That's it.

Now to install .crx file simply drag and drop that file .crx on chrome
extension page. It will get install without any problem. Now open
chrome://apps and see "postmessage tool" icon.

Rest you know right what to do.

On Tuesday, December 7, 2021, gprime31 ***@***.***> wrote:
> <
https://ci6.googleusercontent.com/proxy/Y32UjbxSP67w_jH--0j0YKE1U5S0kTtnrEl4EjHbFoVnLmwW1FsiWqch5rNc53diesQ4-FocwawHmovSmecTKd-IcQ5v7BpF1o4u3cdBUzkL2lrkpZ8CtzzDUKXZlm6ltbMirWUmG2NYrptA8pRi7WupyRCEx6r5=s0-d-e1-ft#https://user-images.githubusercontent.com/44535257/145044310-62458ad6-47ad-4ceb-bcfd-a2599b99f603.png
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci6.googleusercontent.com/proxy/dZOkqOIiUprV56D_s1qOpqxaTDSSYLtNb3Ex1w3QPRwenrfE3ltg6k6fTChlDRYMSwX7mtBDE_8GjpkFFVw42m-wwPGMyuMMMF61wrbOUGHR7aGBCAGq5Cnu1Q1jPv_yusgjGhTZIXpfzE7SCeYnLf398LGe3Jrttsi3qvByY5bsXA7xvsUX1GSV8hDBsxAM14rtN8CNvXWmvDjbRD2kcwR5gXjDV-FDkjPy0HeCfw=s0-d-e1-ft#https://github.com/notifications/beacon/AIQF4G4EF32D5QBHH325EO3UPYIU3A5CNFSM5JRJ5LBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHLRRIQA.gif>

**Comment by gprime31** [comment]
dev mode is on
https://github.com/kiranreddyrebel/PostMessage_Fuzz_Tool/issues/3#issuecomment-987960384 top right cornet of pic.

**Comment by gprime31** [comment]
got it

**Comment by gprime31** [comment]
![2021-12-07_10-55](https://user-images.githubusercontent.com/44535257/145062528-41f94385-408e-4822-81f9-c7fc360710db.png)

**Comment by gprime31** [comment]
had to turn dev mode off, then redo everything, then turn it back on. thanks :)

**Comment by gprime31** [comment]
hmm... dosen't seem to pick up window.open
or window.open(url)

**Comment by kiranreddyrebel** [comment]
What window.open ?

Have you installed the script in tampermonkey ? If yes then all set.

Now follow the YouTube video below in repo.

You will get idea how to get started and hack postmessage bugs.

Go on try.
On Tuesday, December 7, 2021, gprime31 ***@***.***> wrote:
> hmm... dosen't seem to pick up window.open
> or window.open(url)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci3.googleusercontent.com/proxy/pvtHJlnJ9FXKx3vU5fAeriFe5QV9tP-q65imvnJ2mLUry7_BXnGHyzEMYnUj3yXcrIToQFHkJHX5AIVj9jcRoBC40Bq7Ayy7OMXCFLzigMSTcnIKmTkTCuVlRAX7lUR_1ZejJ0bOhV1OGcz9pI7LZ8d9NjRh-_m5EOxdJmT3HrmZE9HMO-PscNP5kKUn4PTZRs1CiDV2RDAIXUMG8VC80_rz9C7ZDI7fcN9bFImqvg=s0-d-e1-ft#https://github.com/notifications/beacon/AIQF4G7TMJMRQHHLGSKPZCLUPYWQTA5CNFSM5JRJ5LBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHLSLQCY.gif>

**Comment by gprime31** [comment]
Yes I got it installed and working now.

the window.open is used to get xss in postmessage, tried a few vuln sites but it doesn't detect it in your tool.

for example:

<html>
<body>
<script>
var x=window.open("url here","hack")
setTimeout(function(){w.postMessage('text here','*');},2000);
</script>
</body>
</html>

the vuln code being:

if (data.name === "redacted")
--
  | window.open(data.url, '_blank');
  | else
  | window.location.href = data.url;
  | break;
  | case redacted_URL:
  | if (data.type === 'SameWindow')
  | window.location.href = data.url;
  | else if (data.type === 'NewWindow')
  | window.open(data.url, '_blank');
  | else if (data.type === 'PopUp')
  | window.open(data.url);

so your tool should have found window.open.

**Comment by gprime31** [comment]
so can you add window.open to the scan list? so it looks for it?
